# <center>(Bonus) Lab 11 &ndash; DATA 3401 (Fall 2022)</center>

## Lab Date: 12/2
## Due Date 12/11 (at 11:59pm) 

## Lab Description
The purpose of this lab is for you to become more familiar object oriented programming by creating a matrix class.

**Important Note!!!** You are **not** allowed to use numpy in this lab. The purpose of the lab is to give you experience writing a class yourself and to appreciate what numpy does in the background for you automatically.

Code at the end of the lab is available for your use to do many standard matrix functions. Note that you may need to modify them if you use them to make methods inside your Matrix class.

# Matrix Class
The following code gives a basic matrix class with the following properties:
1. Matrices are be represented as lists of lists as we have done before
1. The class can be initialized in 2 ways:
    1. with arguments `n` and `m`, the size of the matrix. A newly instanciated matrix will contain all zeros.
    1. with a list of lists of values. Note that since we are using lists of lists to implement matrices, it is possible that a user provides a list so that not all rows have the same number of columns. Test explicitly that the matrix is properly specified.
1. Matrix instances M can be indexed with `M[i][j]` and `M[i,j]`.

In [1]:
class Matrix:
    
    def __init__(self, lst = None, n = None, m = None):
        if lst == None and type(n) == int and type(m) == int:
            self.matrix = [[0]*n for x in range(m)]
        elif (all(type(i) == list for i in lst) and all(len(i) == len(lst[0]) for i in lst)):
            self.matrix = [i for i in lst]
        else:
            print("There is an error in the Matrix!")
            
    def __getitem__(self, index):
        if isinstance(index, int):
            return self.matrix[index]
        elif len(index) == 2:
            i,j = index
            return self.matrix[i][j]
        
    def __str__(self):
        matrix_disp = "["+str(self.matrix[0]).replace(",","")+"\n"
        for i in range(1,len(self.matrix)-1):
            matrix_disp +=" "+str(self.matrix[i]).replace(",","")+"\n"
        matrix_disp +=" "+str(self.matrix[len(self.matrix)-1]).replace(",","")+"]"+"\n"
        return matrix_disp

# Exercise 1 &ndash; Testing the Matrix Class

Test the matrix class as follows:
1. Instantiate a new 2x2 matrix of zeros by passing arguments `n` and `m` to the Matrix class
1. Instantiate a new 3x3 matrix of ones by passing a list of lists to the Matrix class
1. Try to instantiate a matrix with a list of lists, but make the sub-lists different sizes (this will verify that the error state works in the object constructor).
1. Instantiate a 3x3 matrix with entries 1-9 and use print out the (1,1) index entry in both of the ways described in item 3 in the first cell above.
1. Print this full matrix using the `print` command (this verifies that the `__str__` method works).

In [2]:
## Write your code here
matrix1=Matrix(None,int(2),int(2))
print(matrix1)

[[0 0]
 [0 0]]



In [3]:
lst2=[[1,2,3],[4,5,6],[7,8,9]]
matrix2=Matrix(lst2,3,3)
print(matrix2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]



In [4]:
lst3=[[1,5],[3,6,7],[1,5,3,8],[2]]
matrix3=Matrix(lst3)

There is an error in the Matrix!


In [5]:
lst4=[[1,2,3],[4,5,6],[7,8,9]]
matrix3=Matrix(lst4,3,3)
print(matrix3[1,1])

5


In [6]:
print(matrix3[1][1])

5


In [7]:
print(matrix3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]



## Exercise 2 &ndash; Internal methods
Add the following methods to your class (note you may call the functions below in these methods). Make sure to appropriately test the dimensions of the matrices to make sure the operations are correct.
1. `M.scalarmul(c)`: a matrix that is the scalar product $cM$, where every element of $M$ is multiplied by $c$.
1. `M.add(N)`: adds two matrices $M$ and $N$. Don’t forget to test that the sizes of the matrices are compatible for this and all other operations.
1. `M.sub(N)`: subtracts two matrices: $M-N$.
1. `M.mat_mult(N)`: returns a matrix that is the matrix product of two matrices $MN$.
1. `M.element_mult(N)`: returns a matrix that is the element-wise product of two matrices $M$ and $N$.
1. `M.equals(N)`: returns true/false if $M==N$.

In [8]:
# Add these to your class here (copy and paste the class from Exercise 1 to get started)
class Matrix:
    
    def __init__(self, lst = None, n = None, m = None):
        if lst == None and type(n) == int and type(m) == int:
            self.matrix = [[0]*n for x in range(m)]
        elif (all(type(i) == list for i in lst) and all(len(i) == len(lst[0]) for i in lst)):
            self.matrix = [i for i in lst]
        else:
            print("There is an error in the Matrix!")
            
    def __getitem__(self, index):
        if isinstance(index, int):
            return self.matrix[index]
        elif len(index) == 2:
            i,j = index
            return self.matrix[i][j]
        
    def __str__(self):
        matrix_disp = "["+str(self.matrix[0]).replace(",","")+"\n"
        for i in range(1,len(self.matrix)-1):
            matrix_disp +=" "+str(self.matrix[i]).replace(",","")+"\n"
        matrix_disp +=" "+str(self.matrix[len(self.matrix)-1]).replace(",","")+"]"+"\n"
        return matrix_disp
    
    def __scalarmul__(self,c):
        if isinstance(c,int):
            for i in range (len(self.matrix)):
                inner=self.matrix[i]
                for j in range(len(inner)):
                    inner[j]=inner[j]*c
    
    def __add__(self,N):
        #TEST TO SEE IF M AND N ARE COMPATIBLE - assuming
        if len(self.matrix)==len(N):
            for i in range (len(self.matrix)):
                inner=N[i]
                out_in=self.matrix[i]
                for j in range(len(inner)):
                    new_val=(inner[j]+out_in[j])
                    inner[j]=new_val
        print(N)
        
    def __sub__(self,N):
        if len(self.matrix)==len(N):
            for i in range (len(self.matrix)):
                inner=N[i]
                out_in=self.matrix[i]
                for j in range(len(inner)):
                    new_val=(inner[j]-out_in[j])
                    inner[j]=new_val
        print(N)
        
    def __mat_mult__(self,N):
        if len(self.matrix)==len(N):
            for i in range (len(self.matrix)):
                inner=N[i]
                out_in=self.matrix[i]
                for j in range(len(inner)):
                    new_val=(inner[j]*out_in[j])
                    inner[j]=new_val
        print(N)
        
    def __element_mult__(self,N):
        if len(self.matrix)==len(N):
            for i in range (len(self.matrix)):
                inner=N[i]
                out_in=self.matrix[i]
                for j in range(len(inner)):
                    new_val=(inner[j]*out_in[j])
                    inner[j]=new_val
        print(N)
        
    def __equals__(self,N):
        if len(self.matrix)==len(N):
            check=True
            while check==True:
                for i in range(len(self.matrix)):
                    inner=N[i]
                    out_in=self.matrix[i]
                    for j in range(len(inner)):
                            if inner[j]==out_in[j]:
                                check=True
                            else:
                                check=False
                                print("NO MATCH")
        print(N)

In [9]:
# Test your functions thoroughly
ex1=[[1,2,3],[4,5,6],[7,8,9]]
mat1=Matrix(ex1,3,3)
mat1.__scalarmul__(3)
print(mat1)

[[3 6 9]
 [12 15 18]
 [21 24 27]]



In [10]:
ex2=[[4,9,4],[6,0,8],[1,8,7]]
mat2=Matrix(ex1,3,3)
mat2.__add__(ex2)

[[7, 15, 13], [18, 15, 26], [22, 32, 34]]


In [11]:
ex3=[[4,9,4],[6,0,8],[1,8,7]]
mat3=Matrix(ex2,3,3)
mat3.__sub__(ex3)

[[-3, -6, -9], [-12, -15, -18], [-21, -24, -27]]


In [12]:
ex4=[[1,2,3],[4,5,6],[7,8,9]]
mat4=Matrix(ex3,3,3)
mat4.__mat_mult__(ex4)

[[-3, -12, -27], [-48, -75, -108], [-147, -192, -243]]


In [13]:
ex5=[[4,6,2],[0,3,6],[7,5,9]]
mat5=Matrix(ex4,3,3)
mat5.__element_mult__(ex5)

[[-12, -72, -54], [0, -225, -648], [-1029, -960, -2187]]


In [14]:
ex6=[[4,3,2],[2,3,0],[7,1,3]]
mat6=Matrix(ex5,3,3)
mat6.__equals__(ex6)

NO MATCH
NO MATCH
NO MATCH
NO MATCH
NO MATCH
NO MATCH
NO MATCH
NO MATCH
NO MATCH
[[4, 3, 2], [2, 3, 0], [7, 1, 3]]


In [16]:
ex7=[[4,3,2],[2,3,0],[7,1,3]]
mat7=Matrix(ex6,3,3)
print(mat7)
mat7.__equals__(ex7)

[[4 3 2]
 [2 3 0]
 [7 1 3]]



KeyboardInterrupt: 

## Exercise 3
Modify the functions `zeros`, `ones`, and `constant` (of your own or those below) to create objects of your matrix class. Note these should be functions **outside** of your class.

In [30]:
# Write your functions here
class Variations(Matrix): 
    def zeros(self,m,n):
        return [[0]*n for x in range(m)]

    def constant(self,m,n,c):
        return [[c]*n for x in range(m)]

    def ones(self,m,n,c):
        return constant(m,n,1)

In [31]:
# Test your functions here (you should print out each matrix you construct)
a1=[[4,3,2],[2,3,0],[7,1,3]]


## Exercise 4
Overload python operators to appropriately use your functions in 4 and allow expressions like:
- 2*M
- M*2
- M+N
- M-N
- M*N
- M==N
- M=N

1. Matrix assignment ($M=N$) works in 2 ways and can be implemented as a method titled `__eq__`:
        1. If `M_1` and `M_2` are `matrix` instances `M_1=M_2` sets the values of `M_1` to those of `M_2`, if they are the same size. Error otherwise.
        1. Assignment should also work if `M_2` is a list of lists of the correct size rather than an object of the matrix class.

You may find this tutorial useful https://realpython.com/operator-function-overloading.

Demonstrate the basic properties of matrices with your matrix class by creating 2 by 2 example matrices using your Matrix class and illustrating the following:
($A$, $B$, and $C$ are matrices, and $I$ is the identity matrix $\begin{bmatrix} 1 & 0\\ 0 & 1\end{bmatrix}$)

1. $(AB)C = A(BC)$
1. $A(B+C)=AB+AC$
1. $AB \neq BA$
1. $AI = A$
1. $AB = 0$ if $B$ is the 0 matrix

In [ ]:
# Modify your class here (copy and paste it from Exercise 2 to get started)
class Matrix:
    
    def __init__(self, lst = None, n = None, m = None):
        if lst == None and type(n) == int and type(m) == int:
            self.matrix = [[0]*n for x in range(m)]
        elif (all(type(i) == list for i in lst) and all(len(i) == len(lst[0]) for i in lst)):
            self.matrix = [i for i in lst]
        else:
            print("There is an error in the Matrix!")
            
    def __getitem__(self, index):
        if isinstance(index, int):
            return self.matrix[index]
        elif len(index) == 2:
            i,j = index
            return self.matrix[i][j]
        
    def __str__(self):
        matrix_disp = "["+str(self.matrix[0]).replace(",","")+"\n"
        for i in range(1,len(self.matrix)-1):
            matrix_disp +=" "+str(self.matrix[i]).replace(",","")+"\n"
        matrix_disp +=" "+str(self.matrix[len(self.matrix)-1]).replace(",","")+"]"+"\n"
        return matrix_disp
    
    def __scalarmul__(self,c):
        if isinstance(c,int):
            for i in range (len(self.matrix)):
                inner=self.matrix[i]
                for j in range(len(inner)):
                    inner[j]=inner[j]*c
    
    def __add__(self,N):
        #TEST TO SEE IF M AND N ARE COMPATIBLE - assuming
        if len(self.matrix)==len(N):
            for i in range (len(self.matrix)):
                inner=N[i]
                out_in=self.matrix[i]
                for j in range(len(inner)):
                    new_val=(inner[j]+out_in[j])
                    inner[j]=new_val
        print(N)
        
    def __sub__(self,N):
        if len(self.matrix)==len(N):
            for i in range (len(self.matrix)):
                inner=N[i]
                out_in=self.matrix[i]
                for j in range(len(inner)):
                    new_val=(inner[j]-out_in[j])
                    inner[j]=new_val
        print(N)
        
    def __mat_mult__(self,N):
        if len(self.matrix)==len(N):
            for i in range (len(self.matrix)):
                inner=N[i]
                out_in=self.matrix[i]
                for j in range(len(inner)):
                    new_val=(inner[j]*out_in[j])
                    inner[j]=new_val
        print(N)
        
    def __element_mult__(self,N):
        if len(self.matrix)==len(N):
            for i in range (len(self.matrix)):
                inner=N[i]
                out_in=self.matrix[i]
                for j in range(len(inner)):
                    new_val=(inner[j]*out_in[j])
                    inner[j]=new_val
        print(N)
        
    def __equals__(self,N):
        if len(self.matrix)==len(N):
            check=True
            while check==True:
                for i in range(len(self.matrix)):
                    inner=N[i]
                    out_in=self.matrix[i]
                    for j in range(len(inner)):
                            if inner[j]==out_in[j]:
                                check=True
                            else:
                                check=False
                                print("NO MATCH")
        print(N)

In [ ]:
# Test your functions here


## Matrix Functions
You can use these freely. Don't forget to run this cell before the rest of your notebook if you call any of these functions directly.

In [ ]:
def zeros(m,n):
    return [[0]*n for x in range(m)]

def constant(m,n,c):
    return [[c]*n for x in range(m)]

def ones(m,n,c):
    return constant(m,n,1)

def eye(n):
    x = zeros(n,n)
    for i in range(n):
        x[i][i]=1
    return x

def is_matrix(matrix):
    if type(matrix)!=list:
        print("Not a matrix")
        return False
    if type(matrix[0])!=list:
        print("Not a matrix")
        return False
    _ = len(matrix[0])
    for i in matrix:
        if len(i)!=_:
            print("Not a matrix")
            return False
    return True

def shape(matrix):
    if not is_matrix(matrix):
        return
    row_len = len(matrix)
    col_len = len(matrix[0])
    return (row_len,col_len)

def is_square_matrix(matrix):
    x,y = matrix_shape(matrix)
    if x != y:
        print("Not a square matrix")
        return False
    return True

def matrix_add(a,b):
    if not is_matrix(a): 
        print("A is not a matrix")
        return 
    if not is_matrix(b):
        print("B is not a matrix")
        return 
    if matrix_shape(a)!=matrix_shape(b):
        print("Matrices must be the same shape")
        return 
    row,col = matrix_shape(a)
    return_matrix = zero_matrix(row,col)
    for i in range(len(a)):
        for j in range(len(a[i])):
            return_matrix[i][j] = a[i][j]+b[i][j]
    return return_matrix

def matrix_neg(matrix):  
    return matrix_scalar_multiply(-1,matrix)

def matrix_sub(a,b):
    return matrix_add(a,matrix_neg(b))

def transpose(matrix):
    if not is_matrix(matrix): 
        print("Error. Not a matrix")
        return 
    col,row = matrix_shape(matrix)
    return_matrix = zero_matrix(row,col)
    for i in range(row):
        for j in range(col):
            return_matrix[i][j]=matrix[j][i]
    return return_matrix

def matrix_scalar_multiply(scalar,matrix):
    if not is_matrix(matrix): 
        print("Error. Not a matrix")
        return 
    row,col = matrix_shape(matrix)
    return_matrix = zero_matrix(row,col)
    for i in range(row):
        for j in range(col):
            return_matrix[i][j]=matrix[i][j]*scalar
    return return_matrix

def matrix_multiply(M1,M2):
    m1,n1=matrix_shape(M1)
    m2,n2=matrix_shape(M2)
    
    if n1==m2:
        
        M3=zero_matrix(m1,n2)
        
        for i in range(m1):
            for j in range(n2):
                # Compute the element
                for k in range(n1):
                    M3[i][j]+=M1[i][k]*M2[k][j]
        return M3
    else:
        print("Error, matrix dimensions do not match.")
    
def elementwise_multiply(M1,M2):
    m1,n1=matrix_shape(M1)
    m2,n2=matrix_shape(M2)
    
    if m1==m2 and n1==n2:
        M3 = zero_matrix(m1,n1)
        for i in range(m1):
            for j in range(n1):
                M3[i][j] = M1[i][j]*M2[i][j]
        return M3
    else:
        print("Error: matrices must be the same shape.")
        
def dot_product(M1,M2):
    m1,n1=matrix_shape(M1)
    m2,n2=matrix_shape(M2)
    
    if m1==m2 and n1==n2:
        dotprod = 0
        for i in range(m1):
            for j in range(n1):
                dotprod += M1[i][j]*M2[i][j]
        return dotprod
    else:
        print("Error: matrices must be the same shape.")